// <auto-generated />
namespace comeagua.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MudançadeReviewIdparaFLoat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MudançadeReviewIdparaFLoat));
        
        string IMigrationMetadata.Id
        {
            get { return "201808220038169_Mudança de ReviewId para FLoat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
